
name: Génération de Tests
on: [push]
jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installer TestGPT
        run: npm install -g testgpt@latest
      - name: Générer les tests
        run: testgpt -i ./vscode/game-in-web/src -m gpt-4
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_Key }}
